export const data = [
  {
    id: 0,
    nombre: 'Paradise',
    descripcion: 'Descripción muy pero que muy muy muy muy laaaaaarga y describiendo cosas sin sentido para que sea una descripción laaarga larga y se muestre un parrafito.',
    categoria: 'inmobiliaria',
    metros_cuadrados: 2000,
    banos: 6,
    habitaciones: 10,
    localidad: 'Valencia',
    precio: 2000000,
  },
  {
    id: 1,
    nombre: 'Dream',
    descripcion: 'Descripción muy pero que muy muy muy muy laaaaaarga y describiendo cosas sin sentido para que sea una descripción laaarga larga y se muestre un parrafito.',
    categoria: 'motor',
    tipoMotor: 'moto',
    kilometros: 0,
    precio: 65000,
  },
  {
    id: 2,
    nombre: 'Pc',
    descripcion: 'Descripción muy pero que muy muy muy muy laaaaaarga y describiendo cosas sin sentido para que sea una descripción laaarga larga y se muestre un parrafito.',
    categoria: 'tecnologia',
    estado: 'perfecto',
    precio: 2000,
  },
];
