export const data = [
  {
    id: 0,
    nombre: 'Paradise',
    descripcion: 'Jamón ipsum tócate el Barça aquí no hay tomate. Y a genial picardía los lia charanga vale la sonrisa, orujo mis Alonso y colacao, mi rumbeo Barça una musculitos mete una bola manchego, mis roña paella dolores un Lepe sidra la descafeinado vecinos playita martes 13.',
    categoria: 'inmobiliaria',
    metros_cuadrados: 2000,
    banos: 6,
    habitaciones: 10,
    localidad: 'Valencia',
    precio: 2000000,
  },
  {
    id: 1,
    nombre: 'Dream',
    descripcion: 'Jamón ipsum tócate el Barça aquí no hay tomate. Y a genial picardía los lia charanga vale la sonrisa, orujo mis Alonso y colacao, mi rumbeo Barça una musculitos mete una bola manchego, mis roña paella dolores un Lepe sidra la descafeinado vecinos playita martes 13.',
    categoria: 'motor',
    tipoMotor: 'moto',
    kilometros: 0,
    precio: 65000,
  },
  {
    id: 2,
    nombre: 'Pc',
    descripcion: 'Jamón ipsum tócate el Barça aquí no hay tomate. Y a genial picardía los lia charanga vale la sonrisa, orujo mis Alonso y colacao, mi rumbeo Barça una musculitos mete una bola manchego, mis roña paella dolores un Lepe sidra la descafeinado vecinos playita martes 13.',
    categoria: 'tecnologia',
    estado: 'perfecto',
    precio: 2000,
  },
];
